### ISSUE TITLE
ViewModel расписания

### ISSUE THREAD

**Issue by KriseevM** [Namxobick/unn-mobile#24]
Свойства пока не определены, надо проектировать в зависимости от GUI

**Comment by Tarbat** [comment]
1) Хранение последнего запроса (из строки поиска)
2) Кнопки "перелистывания" недели и поисковая строка (через метод)
3) Календарь (Прогрузка до конца учебного года с подсчетом количества пар в день)
___
Вывод 14-ти дней (В слайдовой версии) // Вывод определенного дня (В "подневной" версии)
Метод подсчет пар в день

**Comment by KriseevM** [comment]
Есть ощущение, что мне проще будет vm написать вместе с вёрсткой, потому что я не до конца осознал как оно взаимодействует с view и проще сразу менять vm, а не просить кого-то изменить интерфейс
Объединять задачи не буду, но переназначу эту на себя

**Comment by KriseevM** [comment]
Думаю, стоит это в одной ветке делать
Я вряд ли больше буду разделять написание вьюмодели и представления в отдельные задачи вообще
