### ISSUE TITLE
Экран с логотипом (самый первый при запуске, вёрстка + viewmodel)

### ISSUE THREAD

**Issue by KriseevM** [Namxobick/unn-mobile#8]
Логика состоит в следующем: 
Экран после запуска в фоне обращается к сервисам хранилища и авторизации, подгружает данные авторизации.
Если их нет - переход на экран логина
Если данные есть, то пытаемся войти.
Если войти не получилось, но интернет есть (сервис авторизации должен предоставить возможность определения), то перебрасываем на страницу авторизации
Если интернета нет - выводим ошибку (и в дальнейшем возможно перебрасываем на главную страницу, если будет офлайн версия)
Если получилось войти - перебрасываем на основную страницу

**Comment by Namxobick** [comment]
![Image](https://github.com/Namxobick/unn-mobile/assets/100288192/224bd8e1-02d6-4654-bc92-6c61154bef50)
